# Generated by Django 6.1.1 on 2026-10-02 21:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('goals', 'Goals achieved'), ('match', 'Not the right match'), ('availability', 'Availability changed'), ('other', 'Other')], max_length=20)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_as_mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_as_mentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('either', 'Either')], default='email', max_length=10)),
                ('slack_handle', models.CharField(blank=True, max_length=60)),
                ('superpower', models.CharField(choices=[('thinking', '🧠 Thinking'), ('coffee', '☕ Coffee'), ('reading', '📚 Reading papers'), ('debugging', '💻 Debugging'), ('explaining', '🗣 Explaining things'), ('other', '✨ Other')], max_length=20)),
                ('superpower_other', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Available'), ('paused', 'Paused'), ('left', 'Not mentoring')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('match_created', 'New match'), ('match_ended', 'Match ended'), ('mentor_left', 'Mentor left')], max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mentoring.mentoringrelationship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mentoringrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('mentor', models.F('mentee')), _negated=True), name='no_self_mentoring'),
        ),
        migrations.AddConstraint(
            model_name='mentoringrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('mentee',), name='one_active_mentor_per_mentee'),
        ),
        migrations.AddConstraint(
            model_name='mentoringrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('mentor', 'mentee'), name='unique_active_pair'),
        ),
        migrations.AddConstraint(
            model_name='mentorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='mentor_capacity_positive'),
        ),
    ]
